### ISSUE TITLE
Question about iOS referrerURL

### ISSUE THREAD

**Issue by marandaneto** [ueman/flutter_referrer_info#2]
The OS calls the `application` method.
Then the plugin is registered via https://github.com/ueman/flutter_referrer_info/blob/7ca8207fe4d1e01f79362934eca822e6bf4ee55f/example/ios/Runner/AppDelegate.swift#L10

but the `application` method that takes an `NSUserActivity` in your library isn't an `override`, so I wonder how this is called automatically?

https://github.com/ueman/flutter_referrer_info/blob/7ca8207fe4d1e01f79362934eca822e6bf4ee55f/ios/Classes/ReferrerPlugin.swift#L24-L31

On Android this should work because of `NewIntentListener`.

**Comment by ueman** [comment]
The plugin class conforms to an Objective-C protocol (`FlutterAppLifecycleDelegate`), which is why it's not marked as override in Swift. (Objective-C-Swift interopt is weird. You conform to protocols by having the same signature without needing to specify it anywhere, and you don't need to implement all methods of a protocol, so it looks like magic 😅)

The magic basically is in 

https://github.com/ueman/flutter_referrer_info/blob/7ca8207fe4d1e01f79362934eca822e6bf4ee55f/ios/Classes/ReferrerPlugin.swift#L10

which sets the plugin class as an application delegate and thus the method is called.

(If this is you doing research for PostHog I have bad news since `FlutterAppLifecycleDelegate` is unfortunately a Flutter mechanism 😕)

**Comment by marandaneto** [comment]
That was me just being curious :D
But I looked at this in the past already and could not find a way to get the `application` with `NSUserActivity` called automatically unless you provide a class to be extended or something which isn't ideal so letting people call `captureX` with their own referral was just easier.

Delegate:

https://github.com/flutter/engine/blob/903809ddc18f3cdc8abf6c7232791fc059db6471/shell/platform/darwin/macos/framework/Source/FlutterAppLifecycleDelegate.mm

Thanks for the context tho.
